---
services:
  eng-ai-agents:
    build:
      context: "."
      dockerfile: ./docker/Dockerfile.dev.cpu
    image: eng-ai-agents
    shm_size: '8gb' # Shared memory size
    user: vscode
    command: /bin/sh -c "while sleep 1000; do :; done"
    # Remove or comment out GPU-related environment variables
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    # Remove the deploy section with GPU configurations
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: ["gpu"]
    #           device_ids: ["all"]
    networks:
      - eng-ai-agents-net

networks:
  eng-ai-agents-net:
    driver: bridge

volumes:
  minio_data:
  rye-cache: